000100*&DOS 01                                                                  
000200*01  SCRPRM01-COMM-AEA.                                                  
000300******************************************************************        
000400*                                                                *        
000500*                     D F                         *        
000600*                   __________________________                       
000700*                                                                *        
000800*    ID        DATE     PG            DESCRITION            *        
000900* D23A      02/04/1994  VWC   DSS SHUTDWN                       *        
      * D51223    02/04/2011  SAH   X1X COMMISION SCHEDUE CHANGE TO  *        
      *                            CAREER                              *        
      *           AGENT-CLASS-CODE IS POPULAT
D IN THE COPY BOOK               
      *           AGENT-ADDRE-CD WILL BE USE FOR VALUES GIVEN BELOW   *        
      *                                                                *        
      *           AGENT-ADDRE-CD VALUES:                               *        
      *                1 = MR.                                         *        
      *                2 = MRS.                                        *        
      *                3 = MIS                                       *        
           
001000*                                                                *        
001100*DXC º D127482 º ADDED AAC AS A NEW VALUE AS A PART OF PURE 1099 *D127482 
      *                PROJECT                                         *D127482 
001200******************************************************************        
