000100*&DOS 01                                                                  
000200*01  SCRPRM01-COMM-AREA.                                                  
000300******************************************************************        
000400*                                                                *        
000500*                    M O D I F I C A T I O N S                   *        
000600*                   ___________________________                          
000700*                                                                *        
000800*    ID        DATE     PGRM              DESCRIPTION            *        
000900* D23A      02/04/1994  VWC   DSS SHUTDOWN                       *        
      * D51223    02/04/2011  SAH   X1X COMMISSION SCHEDULE CHANGE TO  *        
      *                            CAREER                              *        
      *           AGENT-CLASS-CODE IS POPULATED IN THE COPY BOOK               
      *           AGENT-ADDRE-CD WILL BE USE FOR VALUES GIVEN BELOW   *        
      *                                                                *        
      *           AGENT-ADDRE-CD VALUES:                               *        
      *                1 = MR.                                         *        
      *                2 = MRS.                                        *        
      *                3 = MIS                                       *        
           
001000*                                                                *        
001100*DXC º D127482 º ADDED AAC AS A NEW VALUE AS A PART OF PURE 1099 *D127482 
      *                PROJECT                                         *D127482 
001200******************************************************************        
